# Generated by Django 5.2.6 on 2025-09-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('Informática', 'Informática'), ('Administração', 'Administração'), ('Enfermagem', 'Enfermagem'), ('Direito', 'Direito'), ('Apicultura', 'Apicultura'), ('Alimentos', 'Alimentos')], max_length=100),
        ),
    ]
